name: ServiceNow CI/CD Lab (dev -> prod)

on:
  push:
    branches: [ dev ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  ci-dev:
    name: CI on DEV
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Apply Changes on DEV
        uses: ServiceNow/sncicd-apply-changes@1.0
        env:
          nowUsername: ${{ secrets.SN_USERNAME }}
          nowPassword: ${{ secrets.SN_PASSWORD }}
          nowSourceInstance: ${{ secrets.SN_DEV_INSTANCE }}
          appSysID: ${{ secrets.APP_SYS_ID }}
          appScope: ${{ secrets.APP_SCOPE }}
          branch: 'dev'

  promote:
    name: Merge dev -> prod & deploy PROD
    needs: ci-dev
    runs-on: ubuntu-latest
    steps:
      - name: Checkout full history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Merge dev into prod
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git fetch origin dev prod
          git checkout prod
          git merge origin/dev --no-edit
          git push origin prod

      - name: Apply Changes on PROD
        uses: ServiceNow/sncicd-apply-changes@1.0
        env:
          nowUsername: ${{ secrets.SN_USERNAME }}
          nowPassword: ${{ secrets.SN_PASSWORD }}
          nowSourceInstance: ${{ secrets.SN_PROD_INSTANCE }}
          appSysID: ${{ secrets.APP_SYS_ID }}
          appScope: ${{ secrets.APP_SCOPE }}
          branch: 'prod'
